deploymentMode: SingleBinary
loki:
  image:
    tag: 3.0.0
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  schemaConfig:
    configs:
      - from: 2024-05-01
        object_store: filesystem
        store: tsdb
        schema: v13
        index:
          prefix: index_
          period: 24h
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 1Gi
    storageClass: default
read:
  replicas: 0
backend:
  replicas: 0
write:
  replicas: 0
global:
  dnsService: "rke2-coredns-rke2-coredns"